logging.level.org.springframework:
  web: DEBUG

spring.h2.console:
  enabled: true
  path: /h2

spring:
  datasource:
    url: jdbc:h2:file:~/h2db/dasboot
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1
  jpa:
    hibernate.ddl-auto: false  

flyway:
  baseline-on-migrate: true
  
datasource:
  flyway:
    url: jdbc:h2:file:~/h2db/dasboot
    username: sa
    password:
    driver-class-name: org.h2.Driver
